### ISSUE TITLE
Required Python version

### ISSUE THREAD

**Issue by granadata** [joshuaprince/Contrail#1]
It appears that Contrail may require a Python version above 3.5, which is the standard distro for Ubuntu 16.04 LTS.  Example of the error that results: 
```
$ python contrail.py frontend collectstaticTraceback (most recent call last):
  File "contrail.py", line 57, in <module>
    main()
  File "contrail.py", line 38, in main
    subparsers = parser.add_subparsers(required=True, dest="component")
  File "/usr/lib/python3.5/argparse.py", line 1708, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
$ python --version
Python 3.5.2
```

**Comment by hodgesrm** [comment]
Also fails on Python 3.6.  'required' keyword appears to be new in Python 3.7.
